# # -*- coding: utf-8 -*-

# # Form implementation generated from reading ui file 'dialog.ui'
# #
# # Created by: PyQt5 UI code generator 5.15.10
# #
# # WARNING: Any manual changes made to this file will be lost when pyuic5 is
# # run again.  Do not edit this file unless you know what you are doing.


# from PyQt5 import QtCore, QtGui, QtWidgets


# class Ui_SchoolLocatorDialog(object):
#     def setupUi(self, SchoolLocatorDialog):
#         SchoolLocatorDialog.setObjectName("SchoolLocatorDialog")
#         self.verticalLayout = QtWidgets.QVBoxLayout(SchoolLocatorDialog)
#         self.verticalLayout.setObjectName("verticalLayout")
#         self.groupBoxInputs = QtWidgets.QGroupBox(SchoolLocatorDialog)
#         self.groupBoxInputs.setObjectName("groupBoxInputs")
#         self.formLayoutInputs = QtWidgets.QFormLayout(self.groupBoxInputs)
#         self.formLayoutInputs.setObjectName("formLayoutInputs")
#         self.labelPopulationLayer = QtWidgets.QLabel(self.groupBoxInputs)
#         self.labelPopulationLayer.setObjectName("labelPopulationLayer")
#         self.formLayoutInputs.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelPopulationLayer)
#         self.combo_population_layer = QtWidgets.QComboBox(self.groupBoxInputs)
#         self.combo_population_layer.setObjectName("combo_population_layer")
#         self.formLayoutInputs.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.combo_population_layer)
#         self.labelSchoolLayer = QtWidgets.QLabel(self.groupBoxInputs)
#         self.labelSchoolLayer.setObjectName("labelSchoolLayer")
#         self.formLayoutInputs.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelSchoolLayer)
#         self.combo_school_layer = QtWidgets.QComboBox(self.groupBoxInputs)
#         self.combo_school_layer.setObjectName("combo_school_layer")
#         self.formLayoutInputs.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.combo_school_layer)
#         self.labelLandUseLayer = QtWidgets.QLabel(self.groupBoxInputs)
#         self.labelLandUseLayer.setObjectName("labelLandUseLayer")
#         self.formLayoutInputs.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelLandUseLayer)
#         self.combo_land_use_layer = QtWidgets.QComboBox(self.groupBoxInputs)
#         self.combo_land_use_layer.setObjectName("combo_land_use_layer")
#         self.formLayoutInputs.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.combo_land_use_layer)
#         self.verticalLayout.addWidget(self.groupBoxInputs)
#         self.groupBoxParameters = QtWidgets.QGroupBox(SchoolLocatorDialog)
#         self.groupBoxParameters.setObjectName("groupBoxParameters")
#         self.formLayoutParameters = QtWidgets.QFormLayout(self.groupBoxParameters)
#         self.formLayoutParameters.setObjectName("formLayoutParameters")
#         self.labelPopulationThreshold = QtWidgets.QLabel(self.groupBoxParameters)
#         self.labelPopulationThreshold.setObjectName("labelPopulationThreshold")
#         self.formLayoutParameters.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelPopulationThreshold)
#         self.spin_population_threshold = QtWidgets.QSpinBox(self.groupBoxParameters)
#         self.spin_population_threshold.setObjectName("spin_population_threshold")
#         self.formLayoutParameters.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spin_population_threshold)
#         self.labelDistanceFromSchools = QtWidgets.QLabel(self.groupBoxParameters)
#         self.labelDistanceFromSchools.setObjectName("labelDistanceFromSchools")
#         self.formLayoutParameters.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelDistanceFromSchools)
#         self.spin_distance_from_schools = QtWidgets.QDoubleSpinBox(self.groupBoxParameters)
#         self.spin_distance_from_schools.setObjectName("spin_distance_from_schools")
#         self.formLayoutParameters.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spin_distance_from_schools)
#         self.labelRestrictedZoneBuffer = QtWidgets.QLabel(self.groupBoxParameters)
#         self.labelRestrictedZoneBuffer.setObjectName("labelRestrictedZoneBuffer")
#         self.formLayoutParameters.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelRestrictedZoneBuffer)
#         self.spin_restricted_zone_buffer = QtWidgets.QDoubleSpinBox(self.groupBoxParameters)
#         self.spin_restricted_zone_buffer.setObjectName("spin_restricted_zone_buffer")
#         self.formLayoutParameters.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spin_restricted_zone_buffer)
#         self.verticalLayout.addWidget(self.groupBoxParameters)
#         self.horizontalLayoutButtons = QtWidgets.QHBoxLayout()
#         self.horizontalLayoutButtons.setObjectName("horizontalLayoutButtons")
#         self.btn_run_analysis = QtWidgets.QPushButton(SchoolLocatorDialog)
#         self.btn_run_analysis.setObjectName("btn_run_analysis")
#         self.horizontalLayoutButtons.addWidget(self.btn_run_analysis)
#         self.btn_close = QtWidgets.QPushButton(SchoolLocatorDialog)
#         self.btn_close.setObjectName("btn_close")
#         self.horizontalLayoutButtons.addWidget(self.btn_close)
#         self.verticalLayout.addLayout(self.horizontalLayoutButtons)
#         self.lbl_status_message = QtWidgets.QLabel(SchoolLocatorDialog)
#         self.lbl_status_message.setObjectName("lbl_status_message")
#         self.verticalLayout.addWidget(self.lbl_status_message)

#         self.retranslateUi(SchoolLocatorDialog)
#         QtCore.QMetaObject.connectSlotsByName(SchoolLocatorDialog)

#     def retranslateUi(self, SchoolLocatorDialog):
#         _translate = QtCore.QCoreApplication.translate
#         SchoolLocatorDialog.setWindowTitle(_translate("SchoolLocatorDialog", "School Locator"))
#         self.groupBoxInputs.setTitle(_translate("SchoolLocatorDialog", "Input Layers"))
#         self.labelPopulationLayer.setText(_translate("SchoolLocatorDialog", "Population Data:"))
#         self.labelSchoolLayer.setText(_translate("SchoolLocatorDialog", "Existing Schools:"))
#         self.labelLandUseLayer.setText(_translate("SchoolLocatorDialog", "Land Use/Zoning:"))
#         self.groupBoxParameters.setTitle(_translate("SchoolLocatorDialog", "Parameters"))
#         self.labelPopulationThreshold.setText(_translate("SchoolLocatorDialog", "Population Threshold:"))
#         self.labelDistanceFromSchools.setText(_translate("SchoolLocatorDialog", "Max Distance from Schools:"))
#         self.labelRestrictedZoneBuffer.setText(_translate("SchoolLocatorDialog", "Restricted Zone Buffer:"))
#         self.btn_run_analysis.setText(_translate("SchoolLocatorDialog", "Run Analysis"))
#         self.btn_close.setText(_translate("SchoolLocatorDialog", "Close"))
#         self.lbl_status_message.setText(_translate("SchoolLocatorDialog", "Status: Ready"))
