# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'school_locator_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SchoolLocatorDialog(object):
    def setupUi(self, SchoolLocatorDialog):
        SchoolLocatorDialog.setObjectName("SchoolLocatorDialog")
        self.verticalLayout = QtWidgets.QVBoxLayout(SchoolLocatorDialog)
        self.verticalLayout.setObjectName("verticalLayout")

        # Input Layers Group
        self.groupBoxInputs = QtWidgets.QGroupBox(SchoolLocatorDialog)
        self.groupBoxInputs.setObjectName("groupBoxInputs")
        self.formLayoutInputs = QtWidgets.QFormLayout(self.groupBoxInputs)
        self.formLayoutInputs.setObjectName("formLayoutInputs")

        # Population Data Input
        self.labelPopulationLayer = QtWidgets.QLabel(self.groupBoxInputs)
        self.labelPopulationLayer.setObjectName("labelPopulationLayer")
        self.formLayoutInputs.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelPopulationLayer)
        self.btn_population_layer = QtWidgets.QPushButton(self.groupBoxInputs)
        self.btn_population_layer.setObjectName("btn_population_layer")
        self.formLayoutInputs.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.btn_population_layer)

        # School Layer Input
        self.labelSchoolLayer = QtWidgets.QLabel(self.groupBoxInputs)
        self.labelSchoolLayer.setObjectName("labelSchoolLayer")
        self.formLayoutInputs.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelSchoolLayer)
        self.btn_school_layer = QtWidgets.QPushButton(self.groupBoxInputs)
        self.btn_school_layer.setObjectName("btn_school_layer")
        self.formLayoutInputs.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.btn_school_layer)

        # River Layer Input
        self.labelRiverLayer = QtWidgets.QLabel(self.groupBoxInputs)
        self.labelRiverLayer.setObjectName("labelRiverLayer")
        self.formLayoutInputs.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelRiverLayer)
        self.btn_river_layer = QtWidgets.QPushButton(self.groupBoxInputs)
        self.btn_river_layer.setObjectName("btn_river_layer")
        self.formLayoutInputs.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btn_river_layer)

        # Boundary Layer Input
        self.labelBoundaryLayer = QtWidgets.QLabel(self.groupBoxInputs)
        self.labelBoundaryLayer.setObjectName("labelBoundaryLayer")
        self.formLayoutInputs.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelBoundaryLayer)
        self.btn_boundary_layer = QtWidgets.QPushButton(self.groupBoxInputs)
        self.btn_boundary_layer.setObjectName("btn_boundary_layer")
        self.formLayoutInputs.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.btn_boundary_layer)

        self.verticalLayout.addWidget(self.groupBoxInputs)

        # Parameters Group
        self.groupBoxParameters = QtWidgets.QGroupBox(SchoolLocatorDialog)
        self.groupBoxParameters.setObjectName("groupBoxParameters")
        self.formLayoutParameters = QtWidgets.QFormLayout(self.groupBoxParameters)
        self.formLayoutParameters.setObjectName("formLayoutParameters")

        # Population Threshold Parameter
        self.labelPopulationThreshold = QtWidgets.QLabel(self.groupBoxParameters)
        self.labelPopulationThreshold.setObjectName("labelPopulationThreshold")
        self.formLayoutParameters.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelPopulationThreshold)
        self.spin_population_threshold = QtWidgets.QSpinBox(self.groupBoxParameters)
        self.spin_population_threshold.setObjectName("spin_population_threshold")
        self.formLayoutParameters.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spin_population_threshold)

        # Distance from Schools Parameter
        self.labelDistanceFromSchools = QtWidgets.QLabel(self.groupBoxParameters)
        self.labelDistanceFromSchools.setObjectName("labelDistanceFromSchools")
        self.formLayoutParameters.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelDistanceFromSchools)
        self.spin_distance_from_schools = QtWidgets.QDoubleSpinBox(self.groupBoxParameters)
        self.spin_distance_from_schools.setObjectName("spin_distance_from_schools")
        self.formLayoutParameters.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spin_distance_from_schools)

        # Restricted Zone Buffer Parameter
        self.labelRestrictedZoneBuffer = QtWidgets.QLabel(self.groupBoxParameters)
        self.labelRestrictedZoneBuffer.setObjectName("labelRestrictedZoneBuffer")
        self.formLayoutParameters.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelRestrictedZoneBuffer)
        self.spin_restricted_zone_buffer = QtWidgets.QDoubleSpinBox(self.groupBoxParameters)
        self.spin_restricted_zone_buffer.setObjectName("spin_restricted_zone_buffer")
        self.formLayoutParameters.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spin_restricted_zone_buffer)

        # River Distance Buffer Parameter
        self.labelRiverDistanceBuffer = QtWidgets.QLabel(self.groupBoxParameters)
        self.labelRiverDistanceBuffer.setObjectName("labelRiverDistanceBuffer")
        self.formLayoutParameters.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelRiverDistanceBuffer)
        self.spin_river_distance_buffer = QtWidgets.QDoubleSpinBox(self.groupBoxParameters)
        self.spin_river_distance_buffer.setObjectName("spin_river_distance_buffer")
        self.formLayoutParameters.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spin_river_distance_buffer)

        self.verticalLayout.addWidget(self.groupBoxParameters)

        # Buttons
        self.horizontalLayoutButtons = QtWidgets.QHBoxLayout()
        self.horizontalLayoutButtons.setObjectName("horizontalLayoutButtons")
        self.btn_run_analysis = QtWidgets.QPushButton(SchoolLocatorDialog)
        self.btn_run_analysis.setObjectName("btn_run_analysis")
        self.horizontalLayoutButtons.addWidget(self.btn_run_analysis)
        self.btn_close = QtWidgets.QPushButton(SchoolLocatorDialog)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayoutButtons.addWidget(self.btn_close)
        self.verticalLayout.addLayout(self.horizontalLayoutButtons)

        # Status Message
        self.lbl_status_message = QtWidgets.QLabel(SchoolLocatorDialog)
        self.lbl_status_message.setObjectName("lbl_status_message")
        self.verticalLayout.addWidget(self.lbl_status_message)

        self.retranslateUi(SchoolLocatorDialog)
        QtCore.QMetaObject.connectSlotsByName(SchoolLocatorDialog)

    def retranslateUi(self, SchoolLocatorDialog):
        _translate = QtCore.QCoreApplication.translate
        SchoolLocatorDialog.setWindowTitle(_translate("SchoolLocatorDialog", "School Locator"))
        self.groupBoxInputs.setTitle(_translate("SchoolLocatorDialog", "Input Layers"))
        self.labelPopulationLayer.setText(_translate("SchoolLocatorDialog", "Population Data:"))
        self.btn_population_layer.setText(_translate("SchoolLocatorDialog", "..."))
        self.labelSchoolLayer.setText(_translate("SchoolLocatorDialog", "Existing Schools:"))
        self.btn_school_layer.setText(_translate("SchoolLocatorDialog", "..."))
        self.labelRiverLayer.setText(_translate("SchoolLocatorDialog", "River Layers:"))
        self.btn_river_layer.setText(_translate("SchoolLocatorDialog", "..."))
        self.labelBoundaryLayer.setText(_translate("SchoolLocatorDialog", "Boundary Layer:"))
        self.btn_boundary_layer.setText(_translate("SchoolLocatorDialog", "..."))
        self.groupBoxParameters.setTitle(_translate("SchoolLocatorDialog", "Parameters"))
        self.labelPopulationThreshold.setText(_translate("SchoolLocatorDialog", "Population Threshold:"))
        self.labelDistanceFromSchools.setText(_translate("SchoolLocatorDialog", "Max Distance from Schools:"))
        self.labelRestrictedZoneBuffer.setText(_translate("SchoolLocatorDialog", "Restricted Zone Buffer:"))
        self.labelRiverDistanceBuffer.setText(_translate("SchoolLocatorDialog", "Min Distance from Rivers:"))
        self.btn_run_analysis.setText(_translate("SchoolLocatorDialog", "Run Analysis"))
        self.btn_close.setText(_translate("SchoolLocatorDialog", "Close"))
        self.lbl_status_message.setText(_translate("SchoolLocatorDialog", "Status: Ready"))
